# Basic osmconf.ini (angepasst für sensible Einrichtungen)

# Tags, bei denen geschlossene Ways als Polygone interpretiert werden
closed_ways_are_polygons=aeroway,amenity,boundary,building,craft,geological,historic,landuse,leisure,military,natural,office,place,shop,sport,tourism,highway=platform,public_transport=platform,healthcare,social_facility

[points]
osm_id=yes
attributes=name,amenity,healthcare,healthcare:speciality,social_facility,social_facility:for
other_tags=yes

[polygons]
osm_id=yes
attributes=name,amenity,healthcare,healthcare:speciality,social_facility,social_facility:for
other_tags=yes

[multipolygons]
osm_id=yes
attributes=name,amenity,healthcare,healthcare:speciality,social_facility,social_facility:for
other_tags=yes

