# osmconf für ÖPNV-Haltestellen (public_transport=platform + highway=bus_stop)


# put here the name of keys, or key=value, for ways that are assumed to be polygons if they are closed
# see http://wiki.openstreetmap.org/wiki/Map_Features
closed_ways_are_polygons=aeroway,amenity,boundary,building,craft,geological,historic,landuse,leisure,military,natural,office,place,shop,sport,tourism,highway=platform,public_transport=platform



[points]
osm_id=yes
attributes=name,public_transport,highway,railway,bus,tram,train,network,operator
other_tags=no


[lines]
osm_id=yes
attributes=name,public_transport,highway,railway,bus,tram,train,network,operator
other_tags=no


[polygons]
osm_id=yes
attributes=name,public_transport,highway,railway,bus,tram,train,network,operator
other_tags=no

[multipolygons]
osm_id=yes
attributes=name,public_transport,highway,railway,bus,tram,train,network,operator
other_tags=no
