# Basic osmconf.ini (angepasst für sensible Playgrounds)

# Tags, bei denen geschlossene Ways als Polygone interpretiert werden
closed_ways_are_polygons=aeroway,amenity,boundary,building,craft,geological,historic,landuse,leisure,military,natural,office,place,shop,sport,tourism,highway=platform,public_transport=platform,healthcare,social_facility



[multipolygons]
osm_id=yes
attributes=name,building
other_tags=no

