# Basic osmconf.ini


# put here the name of keys, or key=value, for ways that are assumed to be polygons if they are closed
# see http://wiki.openstreetmap.org/wiki/Map_Features
closed_ways_are_polygons=aeroway,amenity,boundary,building,craft,geological,historic,landuse,leisure,military,natural,office,place,shop,sport,tourism,highway=platform,public_transport=platform



[points]
osm_id=yes
attributes=name,amenity,isced:level
other_tags=no


[polygons]
osm_id=yes
attributes=name,amenity,isced:level
other_tags=no

[multipolygons]
osm_id=yes
attributes=name,amenity,isced:level
other_tags=no

